version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuarios_db
    ports:
      - "3306:3306"
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app_two
    depends_on:
      - db
    working_dir: /app
    command: ["python", "app.py"]
    ports:
      - "5000:5000"